# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/entsoe',
                'doc_host': 'https://jvanelteren.github.io',
                'git_url': 'https://github.com/jvanelteren/entsoe',
                'lib_path': 'entsoe'},
  'syms': {'entsoe.core': {'entsoe.core.foo': ('core.html#foo', 'entsoe/core.py')}}}
