# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/entsoe',
                'doc_host': 'https://jvanelteren.github.io',
                'git_url': 'https://github.com/jvanelteren/entsoe',
                'lib_path': 'ents'},
  'syms': { 'ents.db': { 'ents.db.create_connection': ('db.html#create_connection', 'ents/db.py'),
                         'ents.db.create_table': ('db.html#create_table', 'ents/db.py'),
                         'ents.db.do': ('db.html#do', 'ents/db.py'),
                         'ents.db.do_df': ('db.html#do_df', 'ents/db.py'),
                         'ents.db.do_special': ('db.html#do_special', 'ents/db.py'),
                         'ents.db.first': ('db.html#first', 'ents/db.py'),
                         'ents.db.len': ('db.html#len', 'ents/db.py')}}}
