# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_db.ipynb.

# %% auto 0
__all__ = ['create_connection', 'len', 'first', 'do', 'do_special', 'do_df', 'create_table']

# %% ../nbs/01_db.ipynb 2
import sqlite3
from sqlite3 import Error
import pandas as pd

# %% ../nbs/01_db.ipynb 3
def create_connection(db_file):
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)


# %% ../nbs/01_db.ipynb 4
def len(conn, table):
    return do(conn, f"SELECT COUNT(*) FROM {table}")

def first(conn, table):
    return do(conn, f"SELECT * FROM {table} LIMIT 5")



# %% ../nbs/01_db.ipynb 5
def do(conn, ins):
    cur =  conn.cursor()
    res = cur.execute(ins).fetchall()
    cur.close()
    return res

def do_special(conn, ins):
    cur = conn.cursor()
    cur.execute(ins)
    conn.commit()
    cur.close()
    
def do_df(conn, ins):
    cur = conn.cursor().execute(ins)
    col_name_list = [tuple[0] for tuple in cur.description]
    res = pd.DataFrame(cur.fetchall(), columns=col_name_list)
    cur.close()
    return res


# %% ../nbs/01_db.ipynb 6
def create_table(conn, create_table_sql):
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
        conn.commit()
    except Error as e:
        print(e)

